#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 14
#SBATCH --time 00:10:00
#SBATCH --partition cpu
#SBATCH --output d2q9-bgk_1024x1024_14_procs.out

#module load languages/intel/2017.01
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
mpirun ./d2q9-bgk ../../input_1024x1024.params ../../obstacles_1024x1024.dat
