#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 2
#SBATCH --ntasks-per-node 28
#SBATCH --time 00:02:00
#SBATCH --partition cpu
#SBATCH --output d2q9-bgk_128x128_56_procs.out

#module load languages/intel/2017.01
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
mpirun ./d2q9-bgk ../../input_128x128.params ../../obstacles_128x128.dat
