#!/bin/bash
#SBATCH --job-name=d2q9-openmp_gpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node 1
#SBATCH --gres=gpu:1
#SBATCH --partition gpu_veryshort
#SBATCH --time 00:01:00
#SBATCH --output d2q9-bgk_gpu_128_2procs.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

cd $SLURM_SUBMIT_DIR

mpirun -l -print-rank-map -ppn 1 -env CUDA_VISIBLE_DEVICES 0 ../../../d2q9-bgk_gpu2 ../../../input_128x128.params ../../../obstacles_128x128.dat : -env CUDA_VISIBLE_DEVICES 1 ../../../d2q9-bgk_gpu2 ../../../input_128x128.params ../../../obstacles_128x128.dat
